{'mail_domain_health': {'owner': '',
                        'name': 'mail_domain_health',
                        'title': 'Mail domain health',
                        'description': 'Overview of mail-domain posture across all monitored '
                                       'domains: authentication (SPF, DMARC, DKIM, BIMI), '
                                       'reputation and transport (DNSBL/RBL, domain blacklists, '
                                       'MTA-STS, DANE) and domain registration expiry. Scoped to '
                                       'the services created by the mail_domain_health special '
                                       'agent.',
                        'context': {},
                        'single_infos': [],
                        'add_context_to_title': True,
                        'topic': 'applications',
                        'sort_index': 90,
                        'is_show_more': False,
                        'icon': None,
                        'hidden': False,
                        'hidebutton': False,
                        'public': True,
                        'packaged': True,
                        'link_from': {},
                        'main_menu_search_terms': [],
                        'mtime': 0,
                        'show_title': True,
                        'mandatory_context_filters': [],
                        'widgets': {'intro': {'type': 'nodata',
                                              'title': 'About this dashboard',
                                              'text': 'Mail domain health overview. The hexagon '
                                                      'summarises the state of every '
                                                      'mail-domain-health service; the tables '
                                                      'below list the current problems and break '
                                                      'the checks down into authentication and '
                                                      'reputation/transport groups. Green means '
                                                      'the corresponding DNS record or reputation '
                                                      'check is in good shape.',
                                              'position': (1, 1),
                                              'size': (50, 18),
                                              'show_title': True,
                                              'context': {},
                                              'single_infos': []},
                                    'service-stats': {'type': 'servicestats',
                                                      'title': 'Mail domain health service states',
                                                      'position': (51, 1),
                                                      'size': (34, 18),
                                                      'show_title': True,
                                                      'single_infos': [],
                                                      'context': {'serviceregex': {'service_regex': '^(SPF|DMARC|DKIM|RBL|Domain '
                                                                                                    'blacklist|MTA-STS|DANE|BIMI|Domain '
                                                                                                    'expiry) ',
                                                                                   'neg_service_regex': ''}}},
                                    'problems': {'type': 'embedded_view',
                                                 'title': 'Current problems (non-OK)',
                                                 'title_url': 'view.py?view_name=svcproblems&service_regex=%5E%28SPF%7CDMARC%7CDKIM%7CRBL%7CDomain+blacklist%7CMTA-STS%7CDANE%7CBIMI%7CDomain+expiry%29+',
                                                 'position': (1, 19),
                                                 'size': (0, 22),
                                                 'show_title': True,
                                                 'datasource': 'services',
                                                 'single_infos': [],
                                                 'context': {'serviceregex': {'service_regex': '^(SPF|DMARC|DKIM|RBL|Domain '
                                                                                               'blacklist|MTA-STS|DANE|BIMI|Domain '
                                                                                               'expiry) ',
                                                                              'neg_service_regex': ''},
                                                             'svcstate': {'st0': '',
                                                                          'st1': 'on',
                                                                          'st2': 'on',
                                                                          'st3': 'on',
                                                                          'stp': ''}},
                                                 'name': 'mdh_problems'},
                                    'authentication': {'type': 'embedded_view',
                                                       'title': 'Authentication (SPF, DMARC, DKIM, '
                                                                'BIMI)',
                                                       'position': (1, 41),
                                                       'size': (0, 20),
                                                       'show_title': True,
                                                       'datasource': 'services',
                                                       'single_infos': [],
                                                       'context': {'serviceregex': {'service_regex': '^(SPF|DMARC|DKIM|BIMI) ',
                                                                                    'neg_service_regex': ''}},
                                                       'name': 'mdh_auth'},
                                    'reputation': {'type': 'embedded_view',
                                                   'title': 'Reputation & transport (RBL, '
                                                            'blacklists, MTA-STS, DANE, expiry)',
                                                   'position': (1, 61),
                                                   'size': (0, -1),
                                                   'show_title': True,
                                                   'datasource': 'services',
                                                   'single_infos': [],
                                                   'context': {'serviceregex': {'service_regex': '^(RBL|Domain '
                                                                                                 'blacklist|MTA-STS|DANE|Domain '
                                                                                                 'expiry) ',
                                                                                'neg_service_regex': ''}},
                                                   'name': 'mdh_reputation'}},
                        'embedded_views': {'mdh_problems': {'datasource': 'services',
                                                            'single_infos': [],
                                                            'browser_reload': 30,
                                                            'layout': 'table',
                                                            'num_columns': 1,
                                                            'column_headers': 'pergroup',
                                                            'context': {'serviceregex': {'service_regex': '^(SPF|DMARC|DKIM|RBL|Domain '
                                                                                                          'blacklist|MTA-STS|DANE|BIMI|Domain '
                                                                                                          'expiry) ',
                                                                                         'neg_service_regex': ''},
                                                                        'svcstate': {'st0': '',
                                                                                     'st1': 'on',
                                                                                     'st2': 'on',
                                                                                     'st3': 'on',
                                                                                     'stp': ''}},
                                                            'painters': [{'name': 'service_state',
                                                                          'parameters': {},
                                                                          'link_spec': None,
                                                                          'tooltip': None,
                                                                          'join_value': None,
                                                                          'column_title': None,
                                                                          'column_type': 'column'},
                                                                         {'name': 'host',
                                                                          'parameters': {},
                                                                          'link_spec': ('views',
                                                                                        'host'),
                                                                          'tooltip': None,
                                                                          'join_value': None,
                                                                          'column_title': None,
                                                                          'column_type': 'column'},
                                                                         {'name': 'service_description',
                                                                          'parameters': {},
                                                                          'link_spec': ('views',
                                                                                        'service'),
                                                                          'tooltip': None,
                                                                          'join_value': None,
                                                                          'column_title': None,
                                                                          'column_type': 'column'},
                                                                         {'name': 'service_icons',
                                                                          'parameters': {},
                                                                          'link_spec': None,
                                                                          'tooltip': None,
                                                                          'join_value': None,
                                                                          'column_title': None,
                                                                          'column_type': 'column'},
                                                                         {'name': 'svc_plugin_output',
                                                                          'parameters': {},
                                                                          'link_spec': None,
                                                                          'tooltip': None,
                                                                          'join_value': None,
                                                                          'column_title': None,
                                                                          'column_type': 'column'},
                                                                         {'name': 'svc_state_age',
                                                                          'parameters': {},
                                                                          'link_spec': None,
                                                                          'tooltip': None,
                                                                          'join_value': None,
                                                                          'column_title': None,
                                                                          'column_type': 'column'},
                                                                         {'name': 'svc_check_age',
                                                                          'parameters': {},
                                                                          'link_spec': None,
                                                                          'tooltip': None,
                                                                          'join_value': None,
                                                                          'column_title': None,
                                                                          'column_type': 'column'}],
                                                            'group_painters': [],
                                                            'sorters': [('svcstate', True, None),
                                                                        ('site_host', False, None)],
                                                            'mustsearch': False,
                                                            'user_sortable': True,
                                                            'play_sounds': False,
                                                            'force_checkboxes': False,
                                                            'mobile': False},
                                           'mdh_auth': {'datasource': 'services',
                                                        'single_infos': [],
                                                        'browser_reload': 30,
                                                        'layout': 'table',
                                                        'num_columns': 1,
                                                        'column_headers': 'pergroup',
                                                        'context': {'serviceregex': {'service_regex': '^(SPF|DMARC|DKIM|BIMI) ',
                                                                                     'neg_service_regex': ''}},
                                                        'painters': [{'name': 'service_state',
                                                                      'parameters': {},
                                                                      'link_spec': None,
                                                                      'tooltip': None,
                                                                      'join_value': None,
                                                                      'column_title': None,
                                                                      'column_type': 'column'},
                                                                     {'name': 'host',
                                                                      'parameters': {},
                                                                      'link_spec': ('views',
                                                                                    'host'),
                                                                      'tooltip': None,
                                                                      'join_value': None,
                                                                      'column_title': None,
                                                                      'column_type': 'column'},
                                                                     {'name': 'service_description',
                                                                      'parameters': {},
                                                                      'link_spec': ('views',
                                                                                    'service'),
                                                                      'tooltip': None,
                                                                      'join_value': None,
                                                                      'column_title': None,
                                                                      'column_type': 'column'},
                                                                     {'name': 'service_icons',
                                                                      'parameters': {},
                                                                      'link_spec': None,
                                                                      'tooltip': None,
                                                                      'join_value': None,
                                                                      'column_title': None,
                                                                      'column_type': 'column'},
                                                                     {'name': 'svc_plugin_output',
                                                                      'parameters': {},
                                                                      'link_spec': None,
                                                                      'tooltip': None,
                                                                      'join_value': None,
                                                                      'column_title': None,
                                                                      'column_type': 'column'},
                                                                     {'name': 'svc_state_age',
                                                                      'parameters': {},
                                                                      'link_spec': None,
                                                                      'tooltip': None,
                                                                      'join_value': None,
                                                                      'column_title': None,
                                                                      'column_type': 'column'},
                                                                     {'name': 'svc_check_age',
                                                                      'parameters': {},
                                                                      'link_spec': None,
                                                                      'tooltip': None,
                                                                      'join_value': None,
                                                                      'column_title': None,
                                                                      'column_type': 'column'}],
                                                        'group_painters': [],
                                                        'sorters': [('svcstate', True, None),
                                                                    ('site_host', False, None)],
                                                        'mustsearch': False,
                                                        'user_sortable': True,
                                                        'play_sounds': False,
                                                        'force_checkboxes': False,
                                                        'mobile': False},
                                           'mdh_reputation': {'datasource': 'services',
                                                              'single_infos': [],
                                                              'browser_reload': 30,
                                                              'layout': 'table',
                                                              'num_columns': 1,
                                                              'column_headers': 'pergroup',
                                                              'context': {'serviceregex': {'service_regex': '^(RBL|Domain '
                                                                                                            'blacklist|MTA-STS|DANE|Domain '
                                                                                                            'expiry) ',
                                                                                           'neg_service_regex': ''}},
                                                              'painters': [{'name': 'service_state',
                                                                            'parameters': {},
                                                                            'link_spec': None,
                                                                            'tooltip': None,
                                                                            'join_value': None,
                                                                            'column_title': None,
                                                                            'column_type': 'column'},
                                                                           {'name': 'host',
                                                                            'parameters': {},
                                                                            'link_spec': ('views',
                                                                                          'host'),
                                                                            'tooltip': None,
                                                                            'join_value': None,
                                                                            'column_title': None,
                                                                            'column_type': 'column'},
                                                                           {'name': 'service_description',
                                                                            'parameters': {},
                                                                            'link_spec': ('views',
                                                                                          'service'),
                                                                            'tooltip': None,
                                                                            'join_value': None,
                                                                            'column_title': None,
                                                                            'column_type': 'column'},
                                                                           {'name': 'service_icons',
                                                                            'parameters': {},
                                                                            'link_spec': None,
                                                                            'tooltip': None,
                                                                            'join_value': None,
                                                                            'column_title': None,
                                                                            'column_type': 'column'},
                                                                           {'name': 'svc_plugin_output',
                                                                            'parameters': {},
                                                                            'link_spec': None,
                                                                            'tooltip': None,
                                                                            'join_value': None,
                                                                            'column_title': None,
                                                                            'column_type': 'column'},
                                                                           {'name': 'svc_state_age',
                                                                            'parameters': {},
                                                                            'link_spec': None,
                                                                            'tooltip': None,
                                                                            'join_value': None,
                                                                            'column_title': None,
                                                                            'column_type': 'column'},
                                                                           {'name': 'svc_check_age',
                                                                            'parameters': {},
                                                                            'link_spec': None,
                                                                            'tooltip': None,
                                                                            'join_value': None,
                                                                            'column_title': None,
                                                                            'column_type': 'column'}],
                                                              'group_painters': [],
                                                              'sorters': [('svcstate', True, None),
                                                                          ('site_host',
                                                                           False,
                                                                           None)],
                                                              'mustsearch': False,
                                                              'user_sortable': True,
                                                              'play_sounds': False,
                                                              'force_checkboxes': False,
                                                              'mobile': False}}}}
